name: deploy-expiration
on:
    push: 
        branches: 
            - master
        paths: 
            - 'expiration/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd expiration && docker build -t pravash27/expiration .
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push pravash27/expiration