# This is a basic workflow to help you get started with Actions

name: test-payments
on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install
  
