# This is a basic workflow to help you get started with Actions

name: tickets
on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
  
